# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: depot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='depot.proto',
  package='depot',
  serialized_pb=_b('\n\x0b\x64\x65pot.proto\x12\x05\x64\x65pot\"7\n\rTypeSignifier\x12&\n\x04type\x18\x01 \x02(\x0e\x32\x18.depot.ServerMessageType\"&\n\nServerInit\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02ip\x18\x02 \x02(\t\"8\n\x0cServerConfig\x12\x0c\n\x04uuid\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0c\n\x04\x62ody\x18\x03 \x02(\t\"j\n\x0cServerReport\x12\x13\n\x0bserver_uuid\x18\x01 \x02(\t\x12\x0e\n\x06\x65p_num\x18\x03 \x02(\r\x12\x12\n\nhas_config\x18\x04 \x02(\x08\x12\x0c\n\x04\x64one\x18\x05 \x01(\x08\x12\x13\n\x0b\x63onfig_uuid\x18\x06 \x01(\t*5\n\x11ServerMessageType\x12\x08\n\x04INIT\x10\x00\x12\n\n\x06\x43ONFIG\x10\x01\x12\n\n\x06REPORT\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SERVERMESSAGETYPE = _descriptor.EnumDescriptor(
  name='ServerMessageType',
  full_name='depot.ServerMessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INIT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONFIG', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=285,
  serialized_end=338,
)
_sym_db.RegisterEnumDescriptor(_SERVERMESSAGETYPE)

ServerMessageType = enum_type_wrapper.EnumTypeWrapper(_SERVERMESSAGETYPE)
INIT = 0
CONFIG = 1
REPORT = 2



_TYPESIGNIFIER = _descriptor.Descriptor(
  name='TypeSignifier',
  full_name='depot.TypeSignifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='depot.TypeSignifier.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=77,
)


_SERVERINIT = _descriptor.Descriptor(
  name='ServerInit',
  full_name='depot.ServerInit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='depot.ServerInit.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='depot.ServerInit.ip', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=117,
)


_SERVERCONFIG = _descriptor.Descriptor(
  name='ServerConfig',
  full_name='depot.ServerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='depot.ServerConfig.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='depot.ServerConfig.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='depot.ServerConfig.body', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=175,
)


_SERVERREPORT = _descriptor.Descriptor(
  name='ServerReport',
  full_name='depot.ServerReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_uuid', full_name='depot.ServerReport.server_uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ep_num', full_name='depot.ServerReport.ep_num', index=1,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='has_config', full_name='depot.ServerReport.has_config', index=2,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='done', full_name='depot.ServerReport.done', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='config_uuid', full_name='depot.ServerReport.config_uuid', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=283,
)

_TYPESIGNIFIER.fields_by_name['type'].enum_type = _SERVERMESSAGETYPE
DESCRIPTOR.message_types_by_name['TypeSignifier'] = _TYPESIGNIFIER
DESCRIPTOR.message_types_by_name['ServerInit'] = _SERVERINIT
DESCRIPTOR.message_types_by_name['ServerConfig'] = _SERVERCONFIG
DESCRIPTOR.message_types_by_name['ServerReport'] = _SERVERREPORT
DESCRIPTOR.enum_types_by_name['ServerMessageType'] = _SERVERMESSAGETYPE

TypeSignifier = _reflection.GeneratedProtocolMessageType('TypeSignifier', (_message.Message,), dict(
  DESCRIPTOR = _TYPESIGNIFIER,
  __module__ = 'depot_pb2'
  # @@protoc_insertion_point(class_scope:depot.TypeSignifier)
  ))
_sym_db.RegisterMessage(TypeSignifier)

ServerInit = _reflection.GeneratedProtocolMessageType('ServerInit', (_message.Message,), dict(
  DESCRIPTOR = _SERVERINIT,
  __module__ = 'depot_pb2'
  # @@protoc_insertion_point(class_scope:depot.ServerInit)
  ))
_sym_db.RegisterMessage(ServerInit)

ServerConfig = _reflection.GeneratedProtocolMessageType('ServerConfig', (_message.Message,), dict(
  DESCRIPTOR = _SERVERCONFIG,
  __module__ = 'depot_pb2'
  # @@protoc_insertion_point(class_scope:depot.ServerConfig)
  ))
_sym_db.RegisterMessage(ServerConfig)

ServerReport = _reflection.GeneratedProtocolMessageType('ServerReport', (_message.Message,), dict(
  DESCRIPTOR = _SERVERREPORT,
  __module__ = 'depot_pb2'
  # @@protoc_insertion_point(class_scope:depot.ServerReport)
  ))
_sym_db.RegisterMessage(ServerReport)


# @@protoc_insertion_point(module_scope)
